#!/usr/bin/env bash
# Update package lists and install nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo systemctl start nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo pkill -SIGHUP nginx
