#!/usr/bin/env bash
# A Bash script that configures a new Ubuntu machine
# with the installation of nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
cd var/www/html/
cat "Hello World!" > index.nginx-debian.html
