#!/usr/bin/env bash  

# A Bash script that Configures
# Nginx so that its HTTP response
# contains a custom header
#  (on web-01 and web-02)

# Add a custom header to nginx configuration
sudo sed -i '/http {/a \ \ \ \ add_header X-Served-By "$hostname";' /etc/nginx/nginx.conf

# Check nginx configuration syntax
sudo nginx -t

# If configuration is valid, restart nginx
service nginx restart
