#!/usr/bin/env bash
# A Bash script to install
# and configure a load balancer
# haproxy to be exact

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9
sudo apt-get update -y
sudo apt-get install -y haproxy=2.9.\*

echo \
        "
frontend http_front
        bind *:80
        mode http
        default_backend http_backend
backend http_backend
        mode http
        balance roundrobin
        server 151068-web-01 100.25.29.153
        server 151068-web-02 54.197.46.53" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
