#!/usr/bin/env bash
#This script is printing "Best School" 10 times
ITEMS=("Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School")
for item in "${ITEMS[@]}";do
	echo "$item"
done
