#!/usr/bin/env bash
#This file echo's the minutes and hours
hour=0
minute=0
while [ "$hour" -ne 13 ];do
	minute=1
	echo "Hour: $hour"
	while [ "$minute" -ne 60 ];do
		echo "$minute"
		minute="$((minute+1))"
	done
	hour="$((hour+1))"
done
