#!/usr/bin/env bash
# A bash script that blocks out
# all ports and allow on the few listed
sudo apt install -f ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
