#!/usr/bin/env bash
# A bash script that blocks out
# all ports and allow on the few listed
sudo apt install -f ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow in ssh/tcp
sudo ufw allow OpenSSH/tcp
sudo ufw allow http/tcp
sudo ufw allow https/tcp
sudo ufw enable
